### ISSUE TITLE
Bad latitude coordinates in (out of 18) CMIP6 historical runs ?

### ISSUE THREAD

**Issue by covey1** [pochedls/xagg#12]
Fourier analysis of 500hPa geopotential heights for two of the CMIP6 models gives results that differ so much from the others that one suspects an error in reporting latitude coordinate values. See nearby graphic. Data in question are from the following PCMDI XML files:
*
[geopotentialWaveAmplitudesCMIP6.pdf](https://github.com/pochedls/xagg/files/3678471/geopotentialWaveAmplitudesCMIP6.pdf)
/p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.BCC.BCC-CSM2-MR.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20181126.0000000.0.xml
*/p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/zg/CMIP6.CMIP.historical.CAMS.CAMS-CSM1-0.r1i1p1f1.mon.zg.atmos.glb-p19-gn.v20190708.0000000.0.xml

According to the WCRP CMIP6 website, the institutions providing this data are:
* Beijing Climate Center, Beijing 100081, China
* Chinese Academy of Meteorological Sciences, Beijing 100081, China
(https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_institution_id.html)

Curt Covey <@yahoo.com>

**Comment by pochedls** [comment]
@covey1 - could you determine whether this is a problem with the xml or the underlying data? If it is a problem with the xml, we can try to fix it or log the issue, but if it is a problem with the underlying netCDF files, perhaps @durack1 or @taylor13 can point you to the place/person where this data issue should be logged (and we can close this issue).

**Comment by durack1** [comment]
@covey1 it may be that you have found a real issue with CMIP6 data. As @pochedls noted, it would be valuable to check this issue is a problem with the underlying netcdf files, and then contact `BCC` who contributed their data so this can be noted as a valid dataset errata - which can be viewed at https://errata.es-doc.org/static/index.html. To start the process, if a real issue is found, you contact the `BCC` contact point, captured in the `contact` netcdf file attribute, so:
```
[duro@ocean ~]$ more /p/user_pub/xclim/CMIP6/CMIP/historical/atmos/mon/tas/CMIP6.CMIP.historical.BCC.BCC-CSM2-MR.r1i1p1f1.mon.tas.atmos.glb-z1-gn.v20181126.0000000.0.xml | grep contact
	<attr name="contact" datatype="String">Dr. Tongwen Wu(twwu@cma.gov.cn)</attr>
```

**Comment by durack1** [comment]
@covey1 this is not a problem with the xml indexing of the CMIP6 data, so will close this issue. Reopen if it turns out we're indexing valid data incorrectly.

**Comment by covey1** [comment]
My mistake--a key script that I wrote had a bug, which reversed the latitudes when it processed these two models.

Sorry about the confusion.

________________________________

**Comment by durack1** [comment]
@covey1 thanks for the update, glad to know you got to the bottom of the problem and it's not something that was attributed to this xagg code
