### ISSUE TITLE
3hr pr for CMIP* amip and historical 

### ISSUE THREAD

**Issue by gleckler1** [pochedls/xagg#15]
Requested for weekly scan
variable: pr
frequency:  **3hr**
experiments:  amip and historical
mip_era:  CMIP5 and CMIP6

**Comment by pochedls** [comment]
@gleckler1 - I just added a cron job for this. It will run Saturday morning. Reopen this if there is an issue or if the xml files have not populated by Monday.

**Comment by gleckler1** [comment]
@pochedls Excellent, thank you for adding this so quickly Steven!
