### ISSUE TITLE
3hr prw for CMIP5/6 amip and historical 

### ISSUE THREAD

**Issue by chengzhuzhang** [pochedls/xagg#23]
@pochedls Hi Steve, would you please consider add 3hr prw 3hr? I'm not sure how many models have this variable as output. But it will be useful for convection onset analysis. Thank you!

variable: prw
frequency: 3hr
experiments: amip and historical
mip_era: CMIP5 and CMIP6

**Comment by chengzhuzhang** [comment]
Thank you, @pochedls !

**Comment by pochedls** [comment]
@chengzhuzhang - no problem - these xmls should populate over the weekend. Let me know if you don't see them.
