### ISSUE TITLE
CESM CFMIP files missing

### ISSUE THREAD

**Issue by pochedls** [pochedls/xagg#27]
Some CESM data that is included in [runSettings](https://github.com/pochedls/xagg/blob/master/runSettings.py) and for which we have data is not producing xml files. 

It appears this is related to an issue with cdscan (re)-documented [here](https://github.com/CDAT/cdms/issues/397) for which there is a fix.

**Comment by pochedls** [comment]
@mzelinka - follow updates [here](https://github.com/CDAT/cdms/issues/397) in the cdms repository (or here in the xagg repository).

**Comment by pochedls** [comment]
@mzelinka - note that the ticket about this was just [closed](https://github.com/CDAT/cdms/issues/397). We might be able to reset those cdscans and re-scan this data in the near future.

**Comment by pochedls** [comment]
@mzelinka and @durack1: 

I have updated to CDAT 8.2.1 and I think this issue is fixed:

`cdscan -x test.xml /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/*.nc`

> CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/*.nc
> Finding common directory ...
> Common directory: /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/
> Scanning files ...
> /p/css03/esgf_publish/CMIP6/CFMIP/NCAR/CESM2/amip-4xCO2/r1i1p1f1/CFmon/clisccp/gn/v20200124/clisccp_CFmon_CESM2_amip-4xCO2_r1i1p1f1_gn_197901-201412.nc
> Setting reference time units to days since 0001-01-01 00:00:00
> Warning: Axis values for axis plev_bnds are not monotonic: [100000.  80000.  80000.  68000.  68000.  56000.  56000.  44000.  44000.
>   31000.  31000.  18000.  18000.      0.]
> Warning: Resetting axis plev_bnds values to: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
> test.xml written

For reference, this is the current summary of errors from cdscan (so we can compare after updating the environment). 

| Error | n |
| - | -:|
| CDMS I/O error: Determining type of file | 4 |
| Invalid relative time units | 6983 |
| No write | 6875 |
| No write: filesize of zero | 4129 |
| RuntimeError: Dimension time in files | 56 |
| Other | 23 |

**I am considering updating the xagg environment to the nightly version of cdms2 (CDAT8.2.1) and then resetting the directories that have failed scans, which will allow them to be re-scanned and should fix this issue. Any objections?**

**Comment by durack1** [comment]
@pochedls this is great progress, I am sure that @jasonb5, @downiec and @forsyth2 may also be interested in the outcome of the updated scan.

Absolutely zero objections from me

**Comment by mzelinka** [comment]
Sounds good to me. Thanks Steve!

**Comment by pochedls** [comment]
We now have an xml file for the test directory: 

`/p/user_pub/xclim/CMIP6/CFMIP/amip-4xCO2/atmos/mon/clisccp/CMIP6.CFMIP.amip-4xCO2.NCAR.CESM2.r1i1p1f1.mon.clisccp.atmos.glb-p7c-gn.v20200124.0000000.0.xml`

Error Stats (I don't think this is all due to the CDAT version, but some are):
| Error | n | Difference | 
| - | - | - | 
| CDMS I/O error: Determining type of file    | 1 | -3 | 
| Invalid relative time units | 5376 | -1607 |
| No write    | 1751 | -5124 | 
| No write: filesize of zero  | 2922 | -1207 |
| RuntimeError: Dimension time in files   | 41 | -15 | 
| Other | 17 | -6 |

Closing this out.

**Comment by durack1** [comment]
@pochedls thanks for doing this, it's a great, great improvement, yay!

@jasonb5, @downiec, @forsyth2, @muryanto1, @abdulla1 (I hope I haven't missed anyone), thanks so much for all your work over the last months, this is a HUGE improvement for the usability of CDAT. We have a huge "test suite" archive with the millions of CMIP6, CMIP5 and CMIP3 files we have online, so such testing should be a perfect way to work out many of those opaque and difficult to reproduce bugs
