### ISSUE TITLE
NPROC limits being hit

### ISSUE THREAD

**Issue by durack1** [pochedls/xagg#3]
This error is not a bug in software, but rather in the env and config of a user and machine, so dropping it here in case it happens again.
```
(xagg) duro@ocean:[xagg]:[master]:[11288]> ./xagg.py --outputDirectory ~/tmp > log.txt
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable                                
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 1032773 max                                          
OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable                                
OpenBLAS blas_thread_init: RLIMIT_NPROC 1024 current, 1032773 max
...
```

This requires an edit to the (RHEL6) `/etc/security/limits.conf` file, increasing the nproc limit above the default of 1024
```
#<domain>      <type>  <item>         <value>
...
#*               soft    core            0
#*               hard    rss             10000
#@student        hard    nproc           20
...
#@student        -       maxlogins       4
duro             soft    nproc           4096 ; # <-- CHANGED THIS
```
The above requires an env refresh, so logout/login to refresh what the shell limits are - if no new session is created new terms inherit from existing terms

**Comment by pochedls** [comment]
@durack1 - I'm not really sure what to do about this. I do have some functionality (e.g., [here](https://github.com/pochedls/xagg/blob/master/fx.py#L1232)) that makes sure the number of processors is not larger than then number of tasks. Not sure how readily available nproc is to Python (is it an environmental variable?).

**Comment by durack1** [comment]
@pochedls there’s nothing to do in the code. This is just a user env problem, but we’ll likely hit it more than once so figured documenting it here made sense. In RHEL7 the path/files will likely be different. Keeping track of thread counts is a challenge

**Comment by durack1** [comment]
This change actually requires a system reboot (RHEL6), as a VNC session refresh does not seem to have solved it
