### ISSUE TITLE
Monthly Database Snapshots

### ISSUE THREAD

**Issue by pochedls** [pochedls/xagg#31]
xagg is currently set to create a zipped backup of the sqlite3 database on a nightly basis. This is starting to take up a lot of space (62GB).

I will plan on storing the most recent 30 days and monthly backups before that (e.g., on the first of the month or the closest backup to that).

**Comment by durack1** [comment]
Got a script for you to hack re this

**Comment by pochedls** [comment]
That brought me from 476 backups and 62GB to 31 backups and 5.8GB.

**Comment by durack1** [comment]
Did you want that copy of a script, or you happy with your trimming?

**Comment by pochedls** [comment]
> Did you want that copy of a script, or you happy with your trimming?

Thanks for offering to share your script. I ran the script (it seemed like you did not object) and it worked as intended so I don't feel like I need to rewrite it.

**Comment by durack1** [comment]
@pochedls fine with me, I think that monthly backups are ideal. As an FYI here is that script circa ~2007, it's Python 2.5 or something
[backup.py.txt](https://github.com/pochedls/xagg/files/5104765/backup.py.txt)
