### ISSUE TITLE
Add monthly aqua experiments to process list

### ISSUE THREAD

**Issue by qinyia** [pochedls/xagg#32]
@pochedls  Hi Steve, could you please consider adding monthly aqua planet simulations? It will be useful for a hierarcy comparison with other AMIP and fully-coupled simulations. Thank you!

frequency: Amon, CFmon
mip_era: CMIP5 and CMIP6
experiments [CMIP5/CMIP6]: aquaControl/aqua-control, aqua4K/aqua-p4K, aqua4xCO2/aqua-4xCO2

**Comment by pochedls** [comment]
@qinyia - no problem - I think this should run tonight. Let me know if the xml files do not populate.

**Comment by qinyia** [comment]
@pochedls Hi Steve, Thanks for your quick response! I guess the run is done because the latest time stamp for these new files is around 7AM this morning. So I check the xml files and find something is missing. 
1) for MRI-CGCM3 model, its xml file for aquaControl is missing. It looks like no aquaControl data locally, but aqua4K and aqua4xCO2 data are available. But I could find the data on 'cmip5 data search' website. 
2) all xml files for aqua-p4K is missing for CMIP6; aqua4xCO2 is missing for CMIP5.

**Comment by pochedls** [comment]
@qinyia - could you see if this data is on the [LLNL node of ESGF](https://esgf-node.llnl.gov/projects/esgf-llnl/)? The xml files only reflect the data that is available locally. 

If it isn't on our node, we can ask Jeff Painter to help replicate it. Or if you download it yourself we can include that data in the xml repository.

**Comment by qinyia** [comment]
@pochedls Yes, I checked it and this data is only on their default node: esgf-data1.diasjp.net 

I only find this specific data is lack. so it might be easier to directly download it by myself. Is there any preferable directory to put this data?
