### ISSUE TITLE
Deal with /badx directories

### ISSUE THREAD

**Issue by pochedls** [pochedls/xagg#7]
The [function](https://github.com/pochedls/xagg/blob/master/fx.py#L383) that finds directories eligible for scanning ignores directories that have a sub-directory. Unfortunately some CMIP data is kept in directories that also include folders of the form /badx/ (where x is a number). These directories are skipped over for scanning (because they have the badx sub-directory). 

For example, the directory `/p/css03/cmip5_css01/data/cmip5/output1/LASG-IAP/FGOALS-s2/abrupt4xCO2/mon/atmos/Amon/r1i1p1/v1/hur/` has the contents:
`bad0/`  
`bad1/`  
`hur_Amon_FGOALS-s2_abrupt4xCO2_r1i1p1_185001-199912.nc`

The path is passed over for scanning because of the two sub-directories. We should modify the scantree code to detect these situations and return the eligible path.

**Comment by durack1** [comment]
@pochedls this snippet might be re-usable
https://github.com/durack1/cmip5/blob/master/make_cmip5_xml.py#L176-L185

**Comment by pochedls** [comment]
I have code similar to that in the parse path ([here](https://github.com/pochedls/xagg/blob/master/fx.py#L297)). The issue is the code that finds eligible directories is similar to [this](https://github.com/durack1/cmip5/blob/master/make_cmip5_xml.py#L173) block. 

I think we might need a separate if statement that is something to the effect of "if the only subdirectories are of the form bad* and there are files in the directory, yield this directory for scanning."
