### ISSUE TITLE
Job not completing

### ISSUE THREAD

**Issue by pochedls** [pochedls/xagg#8]
The nightly cron job has not completed since 8/17. The run lock was in place [now removed]. The log shows that it finished scanning: 

> Start scans
> Sat Aug 17 00:48:29 2019
>
> Sat Aug 17 00:48:29 2019: 831/831 (100.0%) /p/css03/esgf_publish/CMIP6/DCPP/ 

But then doesn't show the subsequent steps (or an error). Typically the log shows the following (once scans are completed): 

> Write statistics to database
> Fri Aug 16 01:56:25 2019
>
> Finished run
> Fri Aug 16 01:56:42 2019

The next missing step is to write the scan results to the database. It is unlikely this happened (the last write time on the .db file is 00:43).

**Comment by pochedls** [comment]
Reran the job and it completed. Not sure why it crashed. Closing for now (lock file was the only problem).

**Comment by durack1** [comment]
@pochedls just catching up with this, had perms changed or something?

**Comment by pochedls** [comment]
@durack1 - I think we would have gotten an error message from that. I have no idea; it seems like the log should have left a trace if it was a Python error.

**Comment by durack1** [comment]
@pochedls interesting, these kind of weird behaviours were typical as I spun up the xml code v1.0, I kept adding more and more diagnostics so when these weird things happened the condition was caught. As you say, you cleaned things up and it ran again, so hopefully it was just a weird one-off.
